### ISSUE TITLE
Different search commands for the same page now showing in dashboard

### ISSUE THREAD

**Issue by GiFuJo** [vigneshrajj/gofind#3]
The dashboard available by typing in `#l` lists only one command per page, but the different search commands still work.

E. g. you can set up:

`#a w https://www.wowhead.com/search?q=%s Wowhead Retail` and
`#a c https://www.wowhead.com/classic/search?q=%s Wowhead Classic`

and both of them work but only the first one created is listed in the `#l` dashboard.

**Comment by vigneshrajj** [comment]
Please take the latest pull and check if that fixes the issue. I have pushed a fix which should probably fix this issue.
You can run this command to recreate the container: `docker compose pull && docker compose up -d`

**Comment by vigneshrajj** [comment]
Also added default arguments in the newer version. You may find that useful too.

**Comment by GiFuJo** [comment]
Perfect, thank you!

Great little piece of software by the way! After a day of use it's already been a real time saver.

**Comment by vigneshrajj** [comment]
Thank you! It also saves me some time daily. I have disabled my search suggestions altogether now. 

Do mention if you have any suggestions or ideas for this project.
